### ISSUE TITLE
Ask the Basel Face Model 2019 version first

### ISSUE THREAD

**Issue by anleleaaa** [unibas-gravis/parametric-face-image-generator#40] opened 2023-01-11 15:49 UTC
Hello, I would like to ask how to generate random Face using Basel Face Model 2019 version (that version is a.h5 file, I will not use),
 I would be very grateful if you can help me

**Comment by BernhardEgger** [comment] 2023-01-12 08:49
this is a duplicate of https://github.com/unibas-gravis/basel-face-model-viewer/issues/24

**Closed as completed by BernhardEgger** 2023-01-12 08:49 UTC
