### ISSUE TITLE
Facebox for frontal faces are not centered

### ISSUE THREAD

**Issue by thogerig** [unibas-gravis/parametric-face-image-generator#8] opened 2018-04-19 09:16 UTC
Hi there,

If facebox cropping is used for the generator, the frontal faces are not centered in the box, but shifted either to the right or to the left. My expectation would be that the facebox is still centered. See the following example (used variable pitch from -x to x and took the two frontal examples):

![0_1](https://user-images.githubusercontent.com/6950000/38982596-93ae26a2-43c2-11e8-8fa1-629dcccc4c66.jpg)
Start

![0_18](https://user-images.githubusercontent.com/6950000/38982580-80c1227e-43c2-11e8-8656-ab25ca456650.jpg)
Front 1 (Shifted, but should be centered?)

![0_19](https://user-images.githubusercontent.com/6950000/38982570-7a77837c-43c2-11e8-90f0-ac976db3751f.jpg)
Front 2 (Shifted, but should be centered?)

![0_37](https://user-images.githubusercontent.com/6950000/38982612-9b9dccdc-43c2-11e8-8db6-abf9c7eb28c0.jpg)
End

**Comment by BernhardEgger** [comment] 2018-04-19 11:18
Do you use  x-translation-distribution or y-translation-distribution?
If yes, this is an expected result. If no that looks like a bug.
Can you share your config file, or a minimal config file reproducing the error. Is the error on the current master?

**Comment by thogerig** [comment] 2018-04-19 12:48
The standard controlled faces script is used, just with the difference of having the facebox. No translation distribution is set.

**Comment by BernhardEgger** [comment] 2018-04-19 13:25
I get the same bug - since facebox is the default setting in the RandomScript that should be fixed before releasing a new version...

**Comment by AdamKortylewski** [comment] 2018-04-19 14:03
The bug is the hardcoded "centershift" in line 258 in Helpers.scala. It should be depending on the pose angle.

**Closed as completed** 2018-04-23 08:38 UTC
